# Site settings
title: My Personal Website
email:
description: > # this means to ignore newlines until "baseurl:"
  It 's my personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Charis Logothetis
email: harislogothetis@gmail.com
facebook_username:
twitter_username:
github_username: haris-git
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Charis Logothetis

# API settings
google_api_key:

# Build settings
markdown: kramdown
